### ISSUE TITLE
Negative value bit shift with bit mask to long 

### ISSUE THREAD

**Issue by fedex03** [adafruit/Adafruit-MAX31855-library#21] opened 2018-04-09 12:55 UTC
Hi there,
looking into work library I found a bug into the temperature computation, in particular when the temperature in negative.

`  if (v & 0x80000000)
  {
    // Negative value, drop the lower 18 bits and explicitly extend sign bits.
    v = 0xFFFFC000 | ((v >> 18) & 0x00003FFFF);
  }`

The bug regards **((v >> 18) & 0x00003FFFF**

Here you perform a bit shift of 18 position to maintain the 14 temperature bit, but if you use this mask 
**0x00003FFFF** you maintain 18 bit.

The right operations is to get a negative temperature are:

``  if (v & 0x80000000) 
  {
    // Negative value, drop the lower 18 bits and explicitly extend sign bits.
    v = 0xFFFFC000 | ((v >> 18) & 0x00003FFF);
  }``

Thanks for you work Adafruit!

Best regards,
Federico

**Comment by Ve2mrx** [comment] 2018-09-02 03:32
Hi!
  Is your issue a duplicate of #https://github.com/adafruit/Adafruit-MAX31855-library/pull/13 ?

Martin

**Comment by caternuson** [comment] 2020-01-15 05:06
Should be fixed with #36 
https://github.com/adafruit/Adafruit-MAX31855-library/releases/tag/1.1.1

**Closed by caternuson** 2020-01-15 05:06 UTC
